name: OmegaCore
version: 1.0
main: fr.ChadOW.omegacore.P
author: ChadOW
api-version: 1.13
commands:
  money:
    description: ""
    aliases: bal
  pay:
    description: ""
  eco:
    description: ""
  rtp:
    description: ""
  monde:
    description: ""
    aliases: [hub, spawn, mo, server, se]
  setrank:
    description: ""
  account:
    description: ""
  job:
    description: ""
  bank:
    description: ""
  claim:
    description: ""
  unclaim:
    description: ""
    aliases: c
  group:
    description: ""
    aliases: g
  hologram:
    description: ""
  rank:
    description: ""
    aliases: [grade, ranks, grades]
  shop:
    description: ""
  help:
    aliases: menu
  back:
    description: ""
  enchant:
    description: ""
  feed:
    description: ""
  fly:
    description: ""
  flyspeed:
    description: ""
  gamemode:
    description: ""
    aliases: [gm]
  getpos:
    description: ""
    aliases: [coords]
  god:
    description: ""
    aliases: [godmode,tgm]
  heal:
    description: ""
  kill:
    description: ""
  list:
    description: ""
  mail:
    description: ""
  nick:
    description: ""
  powertool:
    description: ""
    aliases: [pt]
  repair:
    description: ""
    aliases: [fix]
  sky:
    description: ""
  speed:
    description: ""
  storm:
    description: ""
  suicide:
    description: ""
  sun:
    description: ""
  top:
    description: ""



