name: OmegaCore
version: 1.0
main: fr.ChadOW.omegacore.P
author: ChadOW
depend: [OmegaAPI]
api-version: 1.13
commands:
  money:
    description: ""
    aliases: bal
  pay:
    description: ""
  eco:
    description: ""
  rtp:
    description: ""
  monde:
    description: ""
    aliases: [hub, spawn, mo, server, se]
  setrank:
    description: ""
  account:
    description: ""
  job:
    description: ""
  bank:
    description: ""
  claim:
    description: ""
  unclaim:
    description: ""
  group:
    description: ""
    aliases: g
  hologram:
    description: ""
  rank:
    description: ""
    aliases: [grade, ranks, grades]